import {env} from "cloudflare:workers";
import {seedState,type OSState} from "@/lib/os";
async function save(s:OSState){s.updatedAt=new Date().toISOString();await env.DB.prepare("INSERT INTO operating_state (id,payload,updated_at) VALUES (?,?,?) ON CONFLICT(id) DO UPDATE SET payload=excluded.payload,updated_at=excluded.updated_at").bind(1,JSON.stringify(s),s.updatedAt).run()}
async function read():Promise<OSState>{const r=await env.DB.prepare("SELECT payload FROM operating_state WHERE id = ?").bind(1).first<{payload:string}>();if(r?.payload)return JSON.parse(r.payload);await save(seedState);return seedState}
const uid=()=>crypto.randomUUID();
export async function GET(){try{return Response.json({state:await read()})}catch(e){console.error(e);return Response.json({error:"The operating database is temporarily unavailable."},{status:503})}}
export async function POST(req:Request){try{const x=await req.json() as any,s=await read(),now=new Date().toISOString();
 if(x.command==="create_venture"){const a=x.answers as boolean[];if(!x.name?.trim()||!Array.isArray(a)||a.length!==6)return Response.json({error:"Name and six filter answers are required."},{status:400});const score=a.filter(Boolean).length;s.ventures.unshift({id:uid(),name:x.name.trim(),stage:score===6?"Approved for validation":"Needs improvement",status:score===6?"green":"red",problem:x.problem?.trim()||"Not defined",offer:x.offer?.trim()||"Not defined",recurring:a[4],score,nextAction:score===6?"Design the smallest paid validation experiment.":"Improve or reject failed criteria.",revenue:0,hours:0});s.logs.unshift({id:uid(),at:now,actor:"Jamal",action:`Screened ${x.name.trim()}: ${score}/6 Savoy Filter.`,reason:score===6?"Approved for validation, not launch.":"Failed ventures cannot advance.",reversible:true})}
 else if(x.command==="set_mission_status"){const m=s.missions.find(v=>v.id===x.id);if(!m)return Response.json({error:"Fire Mission not found."},{status:404});if(x.status==="approved"&&s.missions.filter(v=>v.status==="approved"&&v.createdAt.slice(0,10)===now.slice(0,10)).length>=3)return Response.json({error:"The daily three-decision attention budget is full."},{status:409});m.status=x.status;s.logs.unshift({id:uid(),at:now,actor:"Dominic",action:`${x.status} Fire Mission: ${m.title}.`,reason:"Founder decision recorded.",reversible:true})}
 else if(x.command==="run_cycle"){s.agents=s.agents.map(a=>({...a,status:"ready",lastRun:now}));const active=s.ventures.filter(v=>v.stage!=="Rejected"),best=[...active].sort((a,b)=>(b.recurring?1:0)-(a.recurring?1:0)||b.score-a.score)[0];s.briefing={date:now,summary:`Jamal coordinated ${s.agents.length-1} departments across ${active.length} active opportunities. No unverified revenue was recorded.`,opportunity:best?`${best.name}: ${best.nextAction}`:"Capture and screen a venture.",risk:s.missions.some(m=>m.status==="queued")?"A founder decision is waiting in Fire Missions.":"No critical portfolio risk is recorded.",nextAction:s.missions.find(m=>m.status==="queued")?.title||best?.nextAction||"Capture a venture."};s.logs.unshift({id:uid(),at:now,actor:"Jamal",action:"Completed portfolio operating cycle and refreshed the executive briefing.",reason:"Coordinated strategy, market, finance, operations, growth, automation, and risk.",reversible:true})}
 else if(x.command==="add_ledger"){s.ledger.unshift({id:uid(),date:now,ventureId:x.ventureId||"portfolio",revenueGenerated:Number(x.revenueGenerated)||0,revenueProtected:Number(x.revenueProtected)||0,cashSaved:Number(x.cashSaved)||0,hoursSaved:Number(x.hoursSaved)||0,processesAutomated:Number(x.processesAutomated)||0,customerValue:x.customerValue?.trim()||"",knowledge:x.knowledge?.trim()||"",documentation:x.documentation?.trim()||"",improvement:x.improvement?.trim()||"",asset:x.asset?.trim()||""});s.logs.unshift({id:uid(),at:now,actor:"Priya",action:"Posted a Value Ledger entry.",reason:"Measured cash, time, customer value, learning, documentation, and assets.",reversible:true})}
 else if(x.command==="create_mission"){s.missions.unshift({id:uid(),title:x.title?.trim()||"Untitled decision",ventureId:x.ventureId||"portfolio",type:x.type||"Strategic decision",priority:x.priority||"medium",status:"queued",reason:x.reason?.trim()||"Founder approval required.",roi:x.roi?.trim()||"Not quantified",risk:x.risk?.trim()||"Not assessed",alternative:x.alternative?.trim()||"Defer",confidence:Number(x.confidence)||50,createdAt:now});s.logs.unshift({id:uid(),at:now,actor:"Jamal",action:`Escalated Fire Mission: ${x.title||"Untitled decision"}.`,reason:"High-impact decision requires founder approval.",reversible:true})}
 else return Response.json({error:"Unknown command."},{status:400});await save(s);return Response.json({state:s})}catch(e){console.error(e);return Response.json({error:"The command could not be completed. Your input was not discarded."},{status:500})}}
