module.exports = {
  apps: [
    {
      name: "savoy-ventures-os",
      script: "npm",
      args: "run start:production",
      cwd: "/var/www/savos",
      instances: 1,
      exec_mode: "fork",
      autorestart: true,
      max_memory_restart: "1G",
      env: {
        NODE_ENV: "production",
        PORT: "3000",
        SAVOS_DATA_FILE: "/var/lib/savos/os-state.json",
        SAVOS_OWNER_PASSWORD: process.env.SAVOS_OWNER_PASSWORD,
        SAVOS_SESSION_SECRET: process.env.SAVOS_SESSION_SECRET,
        OPENAI_API_KEY: process.env.OPENAI_API_KEY,
        OPENAI_MODEL: process.env.OPENAI_MODEL || "gpt-5.4-mini",
        AUTONOMY_ENABLED: process.env.AUTONOMY_ENABLED || "false",
        AUTONOMY_WORKER_TOKEN: process.env.AUTONOMY_WORKER_TOKEN,
        AUTONOMY_MONTHLY_BUDGET_USD: process.env.AUTONOMY_MONTHLY_BUDGET_USD || "50",
        AUTONOMY_DB_FILE: "/var/lib/savos/autonomy.sqlite",
        OUTREACH_FROM_EMAIL: process.env.OUTREACH_FROM_EMAIL,
      },
    },
    {
      name: "savoy-autonomy-worker",
      script: "./node_modules/.bin/tsx",
      args: "scripts/autonomy-worker.ts",
      cwd: "/var/www/savos",
      instances: 1,
      exec_mode: "fork",
      autorestart: true,
      max_memory_restart: "512M",
      env: {
        NODE_ENV: "production",
        AUTONOMY_API_URL: "http://127.0.0.1:3000/api/autonomy",
        AUTONOMY_DB_FILE: "/var/lib/savos/autonomy.sqlite",
        AUTONOMY_ENABLED: process.env.AUTONOMY_ENABLED || "false",
        AUTONOMY_WORKER_TOKEN: process.env.AUTONOMY_WORKER_TOKEN,
      },
    },
  ],
};
