import {claimDueJob,counts,enqueue,lastCompleted,listJobs,monthlySpend} from "@/lib/autonomy/store";
import {graphConfigured} from "@/lib/microsoft-graph";
import {execute} from "@/lib/autonomy/engine";
import type {JobKind} from "@/lib/autonomy/types";
import {isOwner,unauthorized} from "@/lib/auth";
export const runtime="nodejs";
const authorized=(request:Request)=>Boolean(process.env.AUTONOMY_WORKER_TOKEN)&&request.headers.get("authorization")===`Bearer ${process.env.AUTONOMY_WORKER_TOKEN}`;
export async function GET(request:Request){if(!isOwner(request))return unauthorized();return Response.json({enabled:process.env.AUTONOMY_ENABLED==="true",modelConfigured:!!process.env.OPENAI_API_KEY,deliveryConfigured:graphConfigured(),budgetUsd:Number(process.env.AUTONOMY_MONTHLY_BUDGET_USD||50),estimatedSpendUsd:monthlySpend(),jobs:listJobs(),counts:counts(),lastCycleAt:lastCompleted("operating_cycle")})}
export async function POST(request:Request){const body=await request.json() as {action?:string;kind?:JobKind;payload?:Record<string,unknown>};const worker=authorized(request);if(body.action==="work"){if(!worker)return Response.json({error:"Unauthorized"},{status:401});const job=claimDueJob();return Response.json(job?{job:await execute(job)}:{job:null})}if(body.action==="enqueue"){if(!worker&&!isOwner(request))return unauthorized();const allowed:JobKind[]=["operating_cycle","revenue_hunter","opportunity_score","catalog_intake","catalog_transform","prospect_research","outreach","reply_triage","payment_sync","delivery_router","daily_briefing"];if(!body.kind||!allowed.includes(body.kind))return Response.json({error:"Invalid job kind"},{status:400});return Response.json({job:enqueue(body.kind,body.payload||{})},{status:201})}return Response.json({error:"Unknown action"},{status:400})}
