export const outreachConfig = {
  mailbox: "SavoyVentures@outlook.com",
  founder: "Dominic Savoy",
  phone: "+12404400407",
  website: "https://savoyventures.org",
  checkout: "https://buy.stripe.com/3cI3cvfSX0A47839B6fYY00",
  serviceCheckouts: {
    merchantFeedRescue: "https://buy.stripe.com/5kQ3cv8qvaaEdwr4gMfYY01",
    shopifyImportRescue: "https://buy.stripe.com/7sYbJ18qvfuY4ZV7sYfYY02",
    supplierFileNormalization: "https://buy.stripe.com/14AcN50Y33Mg4ZVaFafYY03",
    amazonListingFileRescue: "https://buy.stripe.com/9B64gz7mreqU4ZVbJefYY04",
    menuCatalogConversion: "https://buy.stripe.com/aFaeVd5ej4Qk1NJ9B6fYY05",
    productImageProductionPack: "https://buy.stripe.com/bJe3cveOT4Qk0JF00wfYY06",
  },
  signaturePreview: "https://savoyventures.org/email/signature.html",
  workflow: [
    "Find retailers with visible product-catalog quality problems.",
    "Verify the business, decision-maker role, and public business contact details.",
    "Score fit for the fixed-scope $250 Catalog Rescue pilot.",
    "Send a personalized message from the connected company mailbox.",
    "Track delivery, replies, follow-ups, checkout clicks, and Stripe payments.",
    "Stop outreach on opt-out, invalid address, complaint, or poor fit.",
    "Open a paid delivery job only after Stripe confirms payment.",
  ],
} as const;
